"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['RecipeBuddy.py']
DATA_FILES = ['Recipe Buddy_MAIN/assets/recipes_data.csv']
OPTIONS = {}

setup(
    app=APP,
    data_files=[],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
